spring.datasource.url=jdbc:postgresql://localhost:5432/post_hub_local?currentSchema=refreshing_knowledge_of_springboot
spring.datasource.username=postgres
spring.datasource.password=admin

spring.flyway.locations=classpath:db/migration,classpath:db/seeds

jwt.secret=heZxikPYEwDz3P3KX4Oa0TnFye3XgxWYe1Q5znTWlE5jxPOHDy67eP0Q+QvT/0dNOxKp/AfpMDxYMLfjR+FfJg==

logging.level.com.post_hub.refreshing_knowledge_of_SpringBoot=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG