spring.profiles.active=local-idea

spring.application.name=refreshing_knowledge_of_SpringBoot
server.servlet.context-path=/
server.port=8189

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=refreshing_knowledge_of_springboot

spring.flyway.enabled=true
spring.flyway.schemas=refreshing_knowledge_of_springboot

jwt.expiration=86400000

#endpoints
end.points.all=/all
end.points.create=/create
end.points.comment=/comment
end.points.dislike=/dislike
end.points.id=/{id}
end.points.login=/login
end.points.logout=/logout
end.points.like=/like
end.points.posts=/posts
end.points.refresh=/refresh
end.points.register=/register
end.points.search=/search
end.points.token=/token
end.points.update=/update
end.points.users=/users