spring.datasource.url=jdbc:postgresql://<host>:5432/<db>?currentSchema=refreshing_knowledge_of_springboot
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}

cors.allowed.origins=remember to set allowed origins for production environment

logging.level.root=WARN
logging.level.org.springframework.web=INFO