CREATE Table comments (
    id BIGSERIAL PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    message varchar(500) NOT NULL,
    post_id BIGSERIAL NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    user_id BIGSERIAL NOT NULL REFERENCES users (id) ON DELETE CASCADE
);